export const SAVE_NAME = "SAVE_PLAYER";
export const SAVE_CLEARTIME = "SAVE_CLEARTIME";

export const SAVE_PUZZLES = "SAVE_PUZZLES";
export const CHANGE_TEXTBOX = "CHANGE_TEXTBOX";
export const CHANGE_PLAYER_ANSWER = "CHANGE_PLAYER_ANSWER";

export const SAVE_PASSWORDS = "SAVE_PASSWORDS";

export const SHOW_PUZZLE_MODAL = "SHOW_PUZZLE_MODAL";
export const HIDE_PUZZLE_MODAL = "HIDE_PUZZLE_MODAL";
