export const SAVE_NAME = "SAVE_PLAYER";
export const SAVE_CLEARTIME = "SAVE_CLEARTIME";
export const COUNT_CLEARTIME = "COUNT_CLEARTIME";
export const REMOVE_PLAYER = "REMOVE_PLAYER";
export const CHECK_PLAYER_REVIEW = "CHECK_PLAYER_REVIEW";

export const SAVE_REVIEWS = "SAVE_REVIEWS";
export const SAVE_REVIEW = "SAVE_REVIEW";

export const SAVE_PUZZLES = "SAVE_PUZZLES";
export const SAVE_PASSWORDS = "SAVE_PASSWORDS";
export const CHANGE_TEXTBOX = "CHANGE_TEXTBOX";
export const CHANGE_PLAYER_ANSWER = "CHANGE_PLAYER_ANSWER";
export const CHANGE_PLAYER_PASSWORD = "CHANGE_PLAYER_PASSWORD";
export const REMOVE_PLAYER_GAME_DATA = "REMOVE_PLAYER_GAME_DATA";
export const SOLVE_PASSWORD = "SOLVE_PASSWORD";
