export const SAVE_NAME = "SAVE_PLAYER";
export const SAVE_CLEARTIME = "SAVE_CLEARTIME";

export const SAVE_PUZZLES = "SAVE_PUZZLES";
export const SAVE_PASSWORDS = "SAVE_PASSWORDS";
export const CHANGE_TEXTBOX = "CHANGE_TEXTBOX";
export const CHANGE_PLAYER_ANSWER = "CHANGE_PLAYER_ANSWER";
export const CHANGE_PLAYER_PASSWORD = "CHANGE_PLAYER_PASSWORD";
export const SOLVE_PASSWORD = "SOLVE_PASSWORD";
